package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jonnyzzz/conductor-loop/internal/storage"
)

func TestRunAgentTaskValidation(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{"task"})
	if err := cmd.Execute(); err == nil {
		t.Fatalf("expected error for missing project")
	}
}

func TestRunAgentJobValidation(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{"job"})
	if err := cmd.Execute(); err == nil {
		t.Fatalf("expected error for missing project")
	}
}

func TestResolveTaskIDAutoGenerates(t *testing.T) {
	id, err := resolveTaskID("")
	if err != nil {
		t.Fatalf("resolveTaskID empty: %v", err)
	}
	if err := storage.ValidateTaskID(id); err != nil {
		t.Errorf("auto-generated task ID %q failed validation: %v", id, err)
	}
	if !strings.HasPrefix(id, "task-") {
		t.Errorf("expected task ID to start with 'task-', got %q", id)
	}
}

func TestResolveTaskIDAcceptsValid(t *testing.T) {
	valid := "task-20260220-153045-my-feature"
	id, err := resolveTaskID(valid)
	if err != nil {
		t.Fatalf("resolveTaskID valid: %v", err)
	}
	if id != valid {
		t.Errorf("expected %q, got %q", valid, id)
	}
}

func TestResolveTaskIDRejectsInvalid(t *testing.T) {
	invalid := []string{
		"my-task",
		"task-foo",
		"random-string",
		"task-2026022-153045-slug",
		"task-20260220-15304-slug",
	}
	for _, id := range invalid {
		_, err := resolveTaskID(id)
		if err == nil {
			t.Errorf("expected error for invalid task ID %q", id)
		}
	}
}

func TestJobAutoGeneratesTaskID(t *testing.T) {
	// Providing --project but no --task should auto-generate a valid task ID.
	// The command will fail at runner.RunJob (no agent configured), but we can
	// verify that the error is NOT about task ID format.
	cmd := newRootCmd()
	cmd.SetArgs([]string{"job", "--project", "my-project"})
	err := cmd.Execute()
	// We expect an error because no agent is configured, but NOT a task ID error.
	if err != nil && strings.Contains(err.Error(), "invalid task ID") {
		t.Errorf("unexpected task ID validation error: %v", err)
	}
}

func TestJobRejectsInvalidTaskID(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{"job", "--project", "my-project", "--task", "invalid-task-id"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error for invalid task ID")
	}
	if !strings.Contains(err.Error(), "invalid task ID") {
		t.Errorf("expected 'invalid task ID' in error, got: %v", err)
	}
}

func TestTaskPrintsAutoGeneratedTaskID(t *testing.T) {
	var stderr bytes.Buffer
	cmd := newRootCmd()
	cmd.SetErr(&stderr)
	cmd.SetArgs([]string{"task", "--project", "my-project"})
	_ = cmd.Execute() // will fail due to no agent, but task ID should be printed first

	out := stderr.String()
	if !strings.HasPrefix(out, "task: task-") {
		t.Errorf("expected stderr to start with 'task: task-', got: %q", out)
	}
}

func TestTaskDoesNotPrintExplicitTaskID(t *testing.T) {
	var stderr bytes.Buffer
	cmd := newRootCmd()
	cmd.SetErr(&stderr)
	explicitID := "task-20260220-153045-my-feature"
	cmd.SetArgs([]string{"task", "--project", "my-project", "--task", explicitID})
	_ = cmd.Execute() // will fail due to no agent

	out := stderr.String()
	if strings.HasPrefix(out, "task: ") {
		t.Errorf("expected no 'task: ...' line when --task is provided, got: %q", out)
	}
}

func TestJobPrintsAutoGeneratedTaskID(t *testing.T) {
	var stderr bytes.Buffer
	cmd := newRootCmd()
	cmd.SetErr(&stderr)
	cmd.SetArgs([]string{"job", "--project", "my-project"})
	_ = cmd.Execute() // will fail due to no agent, but task ID should be printed first

	out := stderr.String()
	if !strings.HasPrefix(out, "task: task-") {
		t.Errorf("expected stderr to start with 'task: task-', got: %q", out)
	}
}

func TestJobDoesNotPrintExplicitTaskID(t *testing.T) {
	var stderr bytes.Buffer
	cmd := newRootCmd()
	cmd.SetErr(&stderr)
	explicitID := "task-20260220-153045-my-feature"
	cmd.SetArgs([]string{"job", "--project", "my-project", "--task", explicitID})
	_ = cmd.Execute() // will fail due to no agent

	out := stderr.String()
	if strings.HasPrefix(out, "task: ") {
		t.Errorf("expected no 'task: ...' line when --task is provided, got: %q", out)
	}
}

func TestRunAgentWrapValidation(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{"wrap"})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("expected error for missing --agent")
	}
	if !strings.Contains(err.Error(), "agent is required") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestJobBatchSubcommandRegistered(t *testing.T) {
	cmd := newJobCmd()
	found := false
	for _, sub := range cmd.Commands() {
		if sub.Name() == "batch" {
			found = true
			break
		}
	}
	if !found {
		t.Fatal("expected batch subcommand on job command")
	}
}

func TestLoadBatchPrompts(t *testing.T) {
	promptFile := filepath.Join(t.TempDir(), "prompt.txt")
	if err := os.WriteFile(promptFile, []byte("from file"), 0o644); err != nil {
		t.Fatalf("write prompt file: %v", err)
	}

	got, err := loadBatchPrompts([]string{"inline"}, []string{promptFile})
	if err != nil {
		t.Fatalf("loadBatchPrompts: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("expected 2 prompts, got %d", len(got))
	}
	if got[0] != "inline" {
		t.Fatalf("unexpected inline prompt: %q", got[0])
	}
	if got[1] != "from file" {
		t.Fatalf("unexpected file prompt: %q", got[1])
	}
}

func TestLoadBatchPromptsRejectsEmptyPrompt(t *testing.T) {
	_, err := loadBatchPrompts([]string{"  "}, nil)
	if err == nil {
		t.Fatal("expected error for empty prompt")
	}
	if !strings.Contains(err.Error(), "empty") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestJobBatchRejectsMismatchedTaskCount(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{
		"job", "batch",
		"--project", "my-project",
		"--agent", "claude",
		"--prompt", "one",
		"--prompt", "two",
		"--task", "task-20260222-010101-one",
	})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("expected error for mismatched task count")
	}
	if !strings.Contains(err.Error(), "must match prompt count") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestJobBatchRejectsInvalidTaskID(t *testing.T) {
	cmd := newRootCmd()
	cmd.SetArgs([]string{
		"job", "batch",
		"--project", "my-project",
		"--agent", "claude",
		"--prompt", "one",
		"--task", "not-a-task-id",
	})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("expected error for invalid task id")
	}
	if !strings.Contains(err.Error(), "invalid task ID") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestResolveWrapProjectIDFromEnv(t *testing.T) {
	t.Setenv("JRUN_PROJECT_ID", "env-project")
	got, err := resolveWrapProjectID("", "")
	if err != nil {
		t.Fatalf("resolveWrapProjectID: %v", err)
	}
	if got != "env-project" {
		t.Fatalf("project=%q, want env-project", got)
	}
}

func TestResolveWrapProjectIDFromWorkingDir(t *testing.T) {
	t.Setenv("JRUN_PROJECT_ID", "")
	got, err := resolveWrapProjectID("", "/tmp/My Project")
	if err != nil {
		t.Fatalf("resolveWrapProjectID: %v", err)
	}
	if got != "my-project" {
		t.Fatalf("project=%q, want my-project", got)
	}
}
